#!/usr/bin/env bash

#
# Execute Php-cs-fixer après le commit.
#
# Nécessite php-cs-fixer.phar à la racine du projet
#

CURRENT_DIRECTORY=`pwd`
GIT_HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PROJECT_DIRECTORY="$GIT_HOOKS_DIR/../.."

cd $PROJECT_DIRECTORY;
PHP_CS_FIXER="php-cs-fixer.phar"

HAS_PHP_CS_FIXER=false

if [ -x "$PHP_CS_FIXER" ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        php php-cs-fixer.phar fix pages;
        git add "$line";
    done
else
    echo "Please install php-cs-fixer, e.g.:"
    echo "Composer require --dev friendsofphp/php-cs-fixer:^2.2.0"
    exit 1;
fi

cd $CURRENT_DIRECTORY;
